/**
 * The CTO Review Package generator (Mission #004A).
 *
 * A pure, deterministic Markdown template — not an AI summary — built
 * entirely from live Bridge data the caller assembles (reports,
 * mission_events, decisions, cto_briefs, the Recommendation Engine's verdict,
 * and the Pre-Review Gate's verdict). This is the "one button" / "copy
 * export for CTO" deliverable: it must be complete enough to paste into
 * ChatGPT without additional explanation, per the mission brief.
 *
 * Deliberately not stored anywhere — regenerating it from current data is
 * always cheap and avoids a second, potentially stale, source of truth.
 */

import type { RecommendationResult } from "./recommendation";
import type { PreReviewGateResult } from "./review-gate";
import type {
  CtoBriefRecord,
  DecisionRecord,
  MissionEventRecord,
  MissionRecord,
  ReportRecord,
} from "./data/types";

export interface CtoReviewPackageInput {
  mission: MissionRecord;
  reports: ReportRecord[];
  events: MissionEventRecord[];
  decisions: DecisionRecord[];
  briefs: CtoBriefRecord[];
  gate: PreReviewGateResult;
  recommendation: RecommendationResult;
  generatedAtIso: string;
}

function section(title: string, body: string): string {
  return `## ${title}\n\n${body.trim() || "_None recorded._"}\n`;
}

function reportBlock(report: ReportRecord): string {
  const agentLabel = report.agent === "hyperagent" ? "HyperAgent" : "Hermes";
  const lines = [
    `- **${agentLabel}** (${report.status}, ${new Date(report.createdAt).toISOString()})`,
    `  - Summary: ${report.summary}`,
  ];
  if (report.evidence) lines.push(`  - Evidence: ${report.evidence}`);
  if (report.risks) lines.push(`  - Risks: ${report.risks}`);
  if (report.recommendation) lines.push(`  - Recommendation: ${report.recommendation}`);
  if (report.requestedDecision) lines.push(`  - Requested decision: ${report.requestedDecision}`);
  if (report.relatedLinks.length) {
    lines.push(`  - Links: ${report.relatedLinks.join(", ")}`);
  }
  return lines.join("\n");
}

function eventBlock(event: MissionEventRecord): string {
  return `- \`${event.eventType}\` — ${event.description} (${event.actor}, ${new Date(event.createdAt).toISOString()})`;
}

function decisionBlock(decision: DecisionRecord): string {
  return `- ${decision.action} by ${decision.actorName} (${new Date(decision.createdAt).toISOString()})${
    decision.notes ? ` — ${decision.notes}` : ""
  }`;
}

function briefBlock(brief: CtoBriefRecord): string {
  return `- **${brief.recommendation.toUpperCase().replace(/_/g, " ")}** — ${brief.summary}\n  - Rationale: ${brief.rationale}${
    brief.generatedByName ? `\n  - Generated by: ${brief.generatedByName}` : ""
  }`;
}

export function buildCtoReviewPackage(input: CtoReviewPackageInput): string {
  const { mission, reports, events, decisions, briefs, gate, recommendation, generatedAtIso } = input;

  const hermesReports = reports.filter((r) => r.agent === "hermes");
  const hyperAgentReports = reports.filter((r) => r.agent === "hyperagent");
  const openBlockers = events.filter((e) => e.eventType === "blocker");
  const openQuestions = events.filter((e) => e.eventType === "question");
  const links = Array.from(new Set(reports.flatMap((r) => r.relatedLinks)));

  const header = [
    `# CTO Review Package — Mission #${mission.code}`,
    "",
    `**${mission.title}**`,
    "",
    `Generated: ${generatedAtIso} · Owner: ${mission.owner} · Phase: ${mission.phase} · Progress: ${mission.progress}%`,
    `Status: ${mission.status}`,
  ].join("\n");

  const gateStatus = gate.ready
    ? "**Pre-Review Gate: PASSED** — all required evidence present."
    : `**Pre-Review Gate: BLOCKED** — missing: ${gate.missing.join(", ")}.`;

  const recommendationBlock = [
    `**Recommended decision (Recommendation Engine):** ${recommendation.recommendation.toUpperCase().replace(/_/g, " ")}`,
    `Rationale: ${recommendation.rationale}`,
  ].join("\n");

  const body = [
    header,
    "",
    gateStatus,
    "",
    recommendationBlock,
    "",
    section("PR / Commit References", links.map((l) => `- ${l}`).join("\n")),
    section(
      "HyperAgent Report(s)",
      hyperAgentReports.map(reportBlock).join("\n\n"),
    ),
    section("Hermes Certification / Report(s)", hermesReports.map(reportBlock).join("\n\n")),
    section(
      "Architecture & Schema Changes",
      hyperAgentReports
        .map((r) => r.evidence)
        .filter(Boolean)
        .join("\n\n") || "",
    ),
    section(
      "Tests",
      reports
        .map((r) => r.evidence)
        .filter((e): e is string => Boolean(e))
        .join("\n"),
    ),
    section("Open Risks", reports.map((r) => r.risks).filter(Boolean).join("\n")),
    section(
      "Rollback Plan",
      reports.map((r) => r.requestedDecision).filter(Boolean).join("\n"),
    ),
    section("Open Questions", openQuestions.map(eventBlock).join("\n")),
    section("Open Blockers", openBlockers.map(eventBlock).join("\n")),
    section("Prior CTO Briefs", briefs.map(briefBlock).join("\n\n")),
    section("Decision History", decisions.map(decisionBlock).join("\n")),
    section("Full Mission Event Timeline", events.map(eventBlock).join("\n")),
    "---",
    "_Generated by Bridge (Kakehashi Digital Headquarters). Reply with Decision, Conditions, Risks, Required Actions, Confidence, and Approval Status — paste your reply back into Bridge's CTO Decision Import to record it._",
  ].join("\n\n");

  return body;
}
