-- Mission #003A — CTO Office Intelligence Framework. Applies to bridge-hq only.
--
-- Design notes (per CEO directive: maintainability, simplicity, auditability,
-- scalability, clear ownership; avoid clever complexity):
-- - "Engineering Memory" is deliberately NOT a new table — it's a filtered
--   read of the existing company_memory table (see getEngineeringMemory in
--   src/lib/data/index.ts). One source of truth for company history.
-- - The Recommendation Engine is deliberately NOT a database table — it's a
--   pure, deterministic function in src/lib/recommendation.ts. Auditable by
--   reading the code; no hidden rules living only in data.
-- - engineering_standards and playbooks are new tables because they are true
--   reference content with their own lifecycle, distinct from company_memory's
--   narrative log and from cto_briefs' generated-artifact shape.

create table public.engineering_standards (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  category text not null, -- e.g. 'process', 'security', 'architecture', 'release'
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.playbooks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  category text not null,
  steps text not null, -- markdown, ordered steps
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create type public.brief_recommendation as enum ('go', 'go_with_conditions', 'no_go');

create table public.cto_briefs (
  id uuid primary key default gen_random_uuid(),
  mission_id uuid references public.missions(id) on delete set null,
  title text not null,
  summary text not null,
  recommendation public.brief_recommendation not null,
  rationale text not null,
  generated_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

alter table public.engineering_standards enable row level security;
alter table public.playbooks enable row level security;
alter table public.cto_briefs enable row level security;

-- Standards & playbooks: reference material, read by all internal roles,
-- authored by ceo/cto only (matches who owns engineering process decisions).
create policy engineering_standards_read on public.engineering_standards for select
  using (public.current_role() in ('ceo', 'cto', 'hyperagent', 'hermes'));
create policy engineering_standards_write on public.engineering_standards for all
  using (public.current_role() in ('ceo', 'cto'))
  with check (public.current_role() in ('ceo', 'cto'));

create policy playbooks_read on public.playbooks for select
  using (public.current_role() in ('ceo', 'cto', 'hyperagent', 'hermes'));
create policy playbooks_write on public.playbooks for all
  using (public.current_role() in ('ceo', 'cto'))
  with check (public.current_role() in ('ceo', 'cto'));

-- CTO Briefs: generated by any internal role (HyperAgent/Hermes produce them
-- as part of their reporting duty, CEO/CTO can also author one directly);
-- read by all internal roles.
create policy cto_briefs_read on public.cto_briefs for select
  using (public.current_role() in ('ceo', 'cto', 'hyperagent', 'hermes'));
create policy cto_briefs_insert on public.cto_briefs for insert
  with check (
    generated_by = auth.uid()
    and public.current_role() in ('ceo', 'cto', 'hyperagent', 'hermes')
  );
